/** Define ids for each page. */
export const PAGE_IDS = {
  ADD_STUFF: 'add-stuff',
  BILL_DETAILS: 'bill-details',
  LANDING: 'landing',
  LIST_BILLS: 'list-bills',
  EMAIL_FORM: 'email-form',
  LIST_STUFF_ADMIN: 'list-stuff-admin',
  MANAGE_DATABASE: 'manage-database',
  MANAGE_ACCOUNTS: 'manage-accounts',
  NOT_AUTHORIZED: 'not-authorized',
  NOT_FOUND: 'not-found',
  SIGN_IN: 'sign-in',
  SIGN_OUT: 'sign-out',
  SIGN_UP: 'sign-up',
  SAVED_BILLS: 'saved-bills',
  AWAITING_REVIEWS: 'awaiting-reviews',
  CREATE_COMMENTS: 'create-comments',
  AWAITING_TESTIMONIES: 'awaiting-testimonies',
  USER_PROFILE: 'user-profile',
  REQUESTED_ACCOUNTS: 'request-accounts',
  REQUESTED_ACCOUNTS_FORM: 'request-accounts-form',
  DRAFT_TESTIMONY: 'draft-testimony',
  ASSIGNED_BILLS: 'assigned-bills',
  LIST_TESTIMONY: 'list-testimony',
};
